### PR TITLE
remove buggy modmenu and add more culling :>

### PR DESCRIPTION
**Pull request by Cartrigger**

### CODE REVIEW

**Comment by Cartrigger** [comment]
DO NOT MERGE YET, I NEED TO TEST

**Comment by computer-catt** [comment]
suspicious

**Comment by Cartrigger** [comment]
should be okay.

**Comment by TecEash1** [comment]
:eyessus:

**Comment by Cartrigger** [comment]
my pr still exists...
when is gonna get pulled

**Pull request merged**
