### PR TITLE
cool pr

### PR DESCRIPTION
**Pull request by Tr1NgleDev**
https://github.com/QuestCraftPlusPlus/QCXR-XR-Wrapper/pull/31

### CODE REVIEW

**Review by thejudge156 — CHANGES_REQUESTED** [review]
3 Things:
Change the files from just copy and pasted to git submodules
Change logged errors to be more professional
Revert any changes done to jniLibs/ and libopenxr_loader.so please
Revert your tab to space changes, IDEs do this for us and the change is confusing + useless

**Comment by thejudge156** [comment]
Also please make the entire PR a little more professional, like the title and description.

**Comment by Tr1NgleDev** [comment]
the description points to another PR which contains the full change log.

**Comment by Tr1NgleDev** [comment]
about your "requested changes" (also it has 4 things not 3)
1) what files bruv? there were no submodules when i forked the repo, and the only files i added are from libcURL (which arent even that many)
2) huh
3) sorry about that, git lfs fucked me up and i accedentally migrated all .so files to lfs. honestly i have no idea how to even change it back bruh. (and if you know how then im guessing you could do that yourself after merging?)
4) i did spaces to tabs change. not tabs to spaces. and only in the wrapper. and i have never seen any IDE do spaces by default

**Comment by Tr1NgleDev** [comment]
also i have no idea how to title this, honestly. It does multiple things at once and across 2 repos

**Comment by Tr1NgleDev** [comment]
also i have no idea how to title this, honestly. It does multiple things at once and across 2 repos

**Comment by Shuenhoy** [comment]
> also i have no idea how to title this, honestly. It does multiple things at once and across 2 repos

Generally, a good practice is to only do one thing in one PR.  Personally I suggest closing this PR and you can `git cherry-pick` the changes to individual branches and PRs.  You can also use `git rebase -i` to re-organize the commits, e.g. merging small or temp commits, rewording to have meaningful commit message, etc.

**Comment by thejudge156** [comment]
> > also i have no idea how to title this, honestly. It does multiple things at once and across 2 repos
> 
> Generally, a good pratice is to only do one thing in one PR. Personally I suggest closing this PR and you can `git cherry-pick` the changes to individual branches and PRs. You can also use `git rebase -i` to re-organize the commits, e.g. merging small or temp commits, rewording to have meaningful commit message, etc.

What he said

**Comment by thejudge156** [comment]
See my discord ping for information.

**Pull request closed without merging**
