### PR TITLE
adds a default memory profile for quest 1

### PR DESCRIPTION
**Pull request by thewiilover**
make changes if needed (probably will be needed)

### CODE REVIEW

**Comment by Cartrigger** [comment]
This won't run
Too little ram allocated

**Comment by thewiilover** [comment]
> This won't run
> 
> Too little ram allocated

That amount came straight from one of your suggestions to me (on discord)

**Comment by Cartrigger** [comment]
Sorry thought about it but with vivecraft it won't

**Comment by thewiilover** [comment]
> Sorry thought about it but with vivecraft it won't


Ok. Guess we can talk about it on vc if your going to be on

**Comment by thewiilover** [comment]
Whoops meant to put a 1 instead of a q lol

**Comment by thewiilover** [comment]
@thejudge156 if you wanna look this over real quick

**Comment by thejudge156** [comment]
It can *sometimes* run. But it is still *very* limited. Use a draft until we get actually tested numbers please.

**Comment by thewiilover** [comment]
> It can _sometimes_ run. But it is still _very_ limited. Use a draft until we get actually tested numbers please.

ok. i have a quest 1 so you just gotta ping me if you need me (im "thewiilover" btw)

**Comment by thewiilover** [comment]
whoops forgot that it would push this commit to my pull request too lol

**Comment by CADIndie** [comment]
Will possibly be done as part of [Pojlib's](https://github.com/QuestCraftPlusPlus/Pojlib/tree/Refactor) refactor (pending work).

**Pull request closed without merging**
