### PR TITLE
Create lameman

### PR DESCRIPTION
**Pull request by LameMan0**
create lameman

### CODE REVIEW

**Comment by KendrickLamar2003** [comment]
You had nothing better to do, didn't you?

**Review by Accountuser99 — COMMENTED** [review]
?

**Comment by LameMan0** [comment]
> You had nothing better to do, didn't you?

I don't
Now create LameMan

**Comment by TecEash1** [comment]
Best update fr

**Comment by LameMan0** [comment]
I know right

**Comment by Novampr** [comment]
Must be pulled, DO IT

**Pull request closed without merging**
